name: Sync to aggregator-repo

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      - name: Push to aggregator-repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git clone https://github.com/ManiJNani/aggregator-repoo.git
          cd aggregator-repoo

          mkdir -p aggregator-repoo
          cp -r ../* ./aggregator-repoo/
          
          git add .
          git commit -m "Sync from aggregator-repoo $(date)"
          git push
